name: Limited functional tests

on:
  pull_request:

jobs:
  functional-limited:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install uv
        uses: astral-sh/setup-uv@v7
      - name: Run functional tests
        env:
          UV_PYTHON: '3.10'
        run: uvx --from rust-just just functional
