name: Run using pipx

on:
  pull_request:
  workflow_call:
  workflow_dispatch:

jobs:
  pipx:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Run gimmegit
        run: |
          set -ex
          package_dir="$PWD"
          mkdir -p demo
          cd demo
          result="$(pipx run --spec "$package_dir" gimmegit --allow-outer-repo -u canonical dwilding/jubilant my-feature)"
          grep --quiet -F 'Cloned repo:' <<< "$result"
          grep --quiet -F '/jubilant/dwilding-my-feature' <<< "$result"
          cd jubilant/dwilding-my-feature
          status="$(pipx run --spec "$package_dir" gimmegit)"
          grep --quiet -F 'jubilant   canonical:main   dwilding:my-feature' <<< "$status"
